services:
  app:
    container_name: gh-metrics
    build: .

    volumes:
      - ./config.toml:/config.toml

    depends_on:
      - timescaledb
      - grafana

  timescaledb:
    container_name: timescaledb
    image: docker.io/timescale/timescaledb:latest-pg15
    restart: always
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password

    volumes:
      - ./timescaledb:/var/lib/postgresql/data

  grafana:
    container_name: grafana
    image: docker.io/grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3003:3000

    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
